export const PLANET_TYPES = {
  EARTH: "Earth",
  FIRE: "Fire",
  AIR: "Air",
  WATER: "Water",
  LIVE: "Liveworld",
  P_O: "Portal to Outer Plane",
  P_F: "Portal to Plane of Fire",
  P_E: "Portal to Plane of Earth",
  P_A: "Portal to Plane of Air",
  P_W: "Portal to Plane of Water",
  P_P: "Portal to Postive Energy Plane",
  P_N: "Portal to Negative Energy Plane",
  EMPTY: "Empty"
}

export const PORTAL_TYPES = [
  'P_O',
  'P_F',
  'P_E',
  'P_A', 
  'P_W',
  'P_P',
  'P_N'
]


export const PLANET_SIZES = {
  FIRE_AND_AIR: {
    A: "Size A",
    B: "Size B", 
    C: "Size C",
    D: "Size D",
    E: "Size E",
    F: "Size F",
    G: "Size G",
    H: "Size H",
    I: "Size I",
    J: "Size J"
  },
  EARTH_AND_WATER: {
    A: "Size A",
    B: "Size B",
    C: "Size C", 
    D: "Size D",
    E: "Size E",
    F: "Size F",
    G: "Size G",
    H: "Size H"
  }
}

export const PLANET_SHAPES = {
  AMORPHOUS: "Amorphous *",
  BELT: "Belt ‡",
  CLUSTER: "Cluster ❖",
  SPHERICAL: "Spherical ●",
  CUBIC: "Cubic □",
  FLATWORLD: "Flatworld ◗",
  ELLIPTICAL: "Elliptical 0",
  REGULAR: "Triangular (Regular) △",
  IRREGULAR: "Triangular (Irregular) ✧"
}

export const PLANET_NAMES = [
"yezecarro",
"hetraorilia",
"nulrichi",
"ducara",
"cieter",
"paezuno",
"luyemia",
"bihogantu",
"dadus B6N",
"llides 092",
"mazuhiri",
"duchuezuno",
"gabrion",
"bonriri",
"ugawa",
"leuter",
"grixeyama",
"moacarro",
"crypso 3",
"grichi F4HQ",
  "usmeaian",
"afrainensian",
"smayrhieli",
"grueriain",
"hastiiot",
"ewhaniote",
"bubraniasque",
"xocran",
"freer",
"thard",
  "eclariaish",
"agrelaian",
"ploangaer",
"preoniaan",
"hotraiiote",
"suslaianian",
"cosper",
"opliensian",
"brieyensish",
"smaubasino",
  "Peteharpocrates",
"Piea",
"Pa-nebt-ma",
"Abaalisaba",
"Nes-a-hor",
"Heh",
"Neb er tcher",
"Ameneman",
"Mi-atum-u",
"Mandonophis",
  "Nabirye",
"Maat",
"Hem-at-rota",
"Selk",
"Bektenhak",
"Renenet",
"Maani",
"Tan-te-bast",
"Amense",
"Anuktata",
"reotadell",
"ogrupia",
"glaellegana",
"phahiaqar",
"iogiran",
  "istiaxath",
"qufanem",
"unnenica",
"faetosia",
"kliacatia",
  "ver",
"khob",
"khill",
"jaarv",
"drolk",
"olar",
"drotuuk",
"druucrab",
"ghugrug",
"dhergoc",
  "oznan",
"vakolk",
"scivkelk",
"morgaec",
"atih",
"snison",
"soovdis",
"skadho",
"uandi",
"joyrod",
  "gnin",
"rat",
"khor",
"brur",
"khurk",
"dralukk",
"frivkib",
"narkarc",
"fravan",
"gnimgorc",
  "gucheturn",
"relvupra",
"lacoria",
"ivomia",
"giuturn",
"ziebos",
"lloonope",
"llonigantu",
"gnosie WE5",
"cromia 5W1A",
  "thuginerth",
"thomucury",
"bathade",
"ocreron",
"biezuno",
"xinia",
"tretiyama",
"nugetera",
"more 6L77",
"crade EK22",
"patrastea",
"chonganov",
"cachilles",
"lodriri",
"cheunope",
"ciogantu",
"gnithumia",
"caaphus",
"crosie S",
"sarvis 1278",
"dorvenaught",
"yeetworld",
"farnkblatt"
]

export const SYSTEM_TYPES = {
  STANDARD: "Standard",
  FIXED: "Fixed",
  RANDOM: "Random Movement",
  SEMI_RANDOM: "Semi-Random Movement",
  SINGLE: "Single Planet",
  VOID: "Void",
  NESTED: "Nested Spheres"
}

export const FANTASY_RACE_NAMES = [
  "Gray Minotaurs",
  "Minotaurs",
  "Half Grendels",
  "Grendels",
  "Free Oni",
  "Oni",
  "Sanguine Giants",
  "Giants",
  "Tundra Gargoyles",
  "Gargoyles",
  "Lava Trogg",
  "Trogg",
  "Primordial Gorgons",
  "Gorgons",
  "Smog Minotaurs",
  "Minotaurs",
  "Aquatic Oni",
  "Oni",
  "Iron Orcs",
  "Orcs",
  "Violet Minotaurs",
  "Minotaurs",
  "Dream Humans",
  "Humans",
  "Sabre Demons",
  "Demons",
  "Haunted Demons",
  "Demons",
  "Noble Centaurs",
  "Centaurs",
  "Grim Golems",
  "Golems",
  "Elite Werewolves",
  "Werewolves",
  "Eastern Grell",
  "Grell",
  "Faerie Angels",
  "Angels",
  "Angels",
  "Nebula Drake",
  "Drake",
  "Lost Grell",
  "Grell",
  "Salt Oceanids",
  "Oceanids",
  "Volcano Gargoyles",
  "Gargoyles",
  "Valley Dragonborn",
  "Dragonborn",
  "Sacred Orcs",
  "Orcs",
  "Obsidian Nymphs",
  "Nymphs",
  "Light Kappa",
  "Kappa",
  "Austere Golems",
  "Golems",
  "Bog Draugr",
  "Draugr",
  "Ivory Goliaths",
  "Goliaths",
  "Dwarf",
  "Elf", 
  "Gnome",
  "Halfling",
  "Human",
  "Tiefling",
  "Arcane",
  "Beholder",
  "Dracon",
  "Dragon",
  "Elmarin",
  "Ephemeral",
  "Giff",
  "Autognome",
  "Kindori",
  "Krajen",
  "Neogi",
  "Scavver",
  "Plasmoid",
  "Moss Minotaurs",
  "Minotaurs",
  "Eerie Gargoyles",
  "Gargoyles",
  "Spectral Sylphs",
  "Sylphs",
  "Doom Merfolk",
  "Merfolk",
  "Lake Hobgoblins",
  "Hobgoblins",
  "Shadow Oni",
  "Oni",
  "Jungle Ents",
  "Ents",
  "Twilight Vampires",
  "Vampires",
  "Fire Kobolds",
  "Kobolds",
  "Boulder Ents",
  "Ents",
  "Stone Ents",
  "Ents",
  "Dirt Goliaths",
  "Goliaths",
  "Dark Halflings",
  "Halflings",
  "Fey Elves",
  "Elves",
  "Thunder Dryads",
  "Dryads",
  "Fallen Undine",
  "Undine",
  "Chasm Giants",
  "Giants",
  "Serpent Grell",
  "Grell",
  "Arachnid Hagravens",
  "Hagravens",
  "Earthen Ogres",
  "Ogres",
]

export const RANDOM_WORDS = [
  "Lightning",
  "Thunder",
  "Ice",
  "Sand",
  "Mana",
  "Gravity",
  "Elemental",
  "Whisper",
  "Aurora"
]

export const PLANET_POSTFIXES = [
  "Alpha",
  "Prime",
  "Core",
  "Delta",
  "Gamma",
  "Epsilon",
  "Zeta",
  "Eta",
  "Theta",
  "Iota",
  "Kappa",
  "Lambda",
  "Mu",
  "Nu",
  "Xi",
  "Omicron",
  "Pi",
  "Rho",
  "Sigma",
  "Tau",
  "Upsilon",
  "Phi",
  "Chi",
  "Psi",
  "Omega"
]

export const SYSTEM_FEATURES = [
  "A <race> fleet patrols this system.",
  "The corpse of a dead deity floats through this system.",
  "The remnants of a huge space battle can be found in this system.",
  "A herd of Kindori migrate around this system.",
  "A hidden <race> outpost is located in this system on an asteroid.",
  "A crew of <race> pirates scours this system for ships to attack.",
  "Millions of floating undead drift through this system."

]