export const PLANET_TYPES = {
  EARTH: "Earth",
  FIRE: "Fire",
  AIR: "Air",
  WATER: "Water",
  LIVE: "Liveworld",
  P_O: "Portal to Outer Plane",
  P_F: "Portal to Plane of Fire",
  P_E: "Portal to Plane of Earth",
  P_A: "Portal to Plane of Air",
  P_W: "Portal to Plane of Water",
  P_P: "Portal to Postive Energy Plane",
  P_N: "Portal to Negative Energy Plane",
  EMPTY: "Empty"
}

export const PORTAL_TYPES = [
  'P_O',
  'P_F',
  'P_E',
  'P_A', 
  'P_W',
  'P_P',
  'P_N'
]


export const PLANET_SIZES = {
  FIRE_AND_AIR: {
    A: "Size A",
    B: "Size B", 
    C: "Size C",
    D: "Size D",
    E: "Size E",
    F: "Size F",
    G: "Size G",
    H: "Size H",
    I: "Size I",
    J: "Size J"
  },
  EARTH_AND_WATER: {
    A: "Size A",
    B: "Size B",
    C: "Size C", 
    D: "Size D",
    E: "Size E",
    F: "Size F",
    G: "Size G",
    H: "Size H"
  }
}

export const PLANET_SHAPES = {
  AMORPHOUS: "Amorphous *",
  BELT: "Belt ‡",
  CLUSTER: "Cluster ❖",
  SPHERICAL: "Spherical ●",
  CUBIC: "Cubic □",
  FLATWORLD: "Flatworld ◗",
  ELLIPTICAL: "Elliptical 0",
  REGULAR: "Triangular (Regular) △",
  IRREGULAR: "Triangular (Irregular) ✧"
}

export const PLANET_NAMES = [
"yezecarro",
"hetraorilia",
"nulrichi",
"ducara",
"cieter",
"paezuno",
"luyemia",
"bihogantu",
"dadus B6N",
"llides 092",
"mazuhiri",
"duchuezuno",
"gabrion",
"bonriri",
"ugawa",
"leuter",
"grixeyama",
"moacarro",
"crypso 3",
"grichi F4HQ",
  "usmeaian",
"afrainensian",
"smayrhieli",
"grueriain",
"hastiiot",
"ewhaniote",
"bubraniasque",
"xocran",
"freer",
"thard",
  "eclariaish",
"agrelaian",
"ploangaer",
"preoniaan",
"hotraiiote",
"suslaianian",
"cosper",
"opliensian",
"brieyensish",
"smaubasino",
  "Peteharpocrates",
"Piea",
"Pa-nebt-ma",
"Abaalisaba",
"Nes-a-hor",
"Heh",
"Neb er tcher",
"Ameneman",
"Mi-atum-u",
"Mandonophis",
  "Nabirye",
"Maat",
"Hem-at-rota",
"Selk",
"Bektenhak",
"Renenet",
"Maani",
"Tan-te-bast",
"Amense",
"Anuktata",
"reotadell",
"ogrupia",
"glaellegana",
"phahiaqar",
"iogiran",
  "istiaxath",
"qufanem",
"unnenica",
"faetosia",
"kliacatia",
  "ver",
"khob",
"khill",
"jaarv",
"drolk",
"olar",
"drotuuk",
"druucrab",
"ghugrug",
"dhergoc",
  "oznan",
"vakolk",
"scivkelk",
"morgaec",
"atih",
"snison",
"soovdis",
"skadho",
"uandi",
"joyrod",
  "gnin",
"rat",
"khor",
"brur",
"khurk",
"dralukk",
"frivkib",
"narkarc",
"fravan",
"gnimgorc"
]

export const SYSTEM_TYPES = {
  STANDARD: "Standard",
  FIXED: "Fixed",
  RANDOM: "Random Movement",
  SEMI_RANDOM: "Semi-Random Movement",
  SINGLE: "Single Planet",
  VOID: "Void",
  NESTED: "Nested Spheres"
}

export const FANTASY_RACE_NAMES = [
  "Gray Minotaurs",
  "Half Grendels",
  "Free Oni",
  "Sanguine Giants",
  "Tundra Gargoyles",
  "Lava Trogg",
  "Primordial Gorgons",
  "Smog Minotaurs",
  "Aquatic Oni",
  "Iron Orcs",
  "Violet Minotaurs",
  "Dream Humans",
  "Sabre Demons",
  "Haunted Demons",
  "Noble Centaurs",
  "Grim Golems",
  "Elite Werewolves",
  "Eastern Grell",
  "Faerie Angels",
  "Nebula Drake",
  "Lost Grell",
  "Salt Oceanids",
  "Volcano Gargoyles",
  "Valley Dragonborn",
  "Sacred Orcs",
  "Obsidian Nymphs",
  "Light Kappa",
  "Austere Golems",
  "Bog Draugr",
  "Ivory Goliaths",
  "Dragonborn",
  "Dwarf",
  "Elf", 
  "Gnome",
  "Halfling",
  "Human",
  "Tiefling",
  "Arcane",
  "Beholder",
  "Dracon",
  "Dragon",
  "Elmarin",
  "Ephemeral",
  "Giff",
  "Kindori",
  "Krajen",
  "Neogi",
  "Scavver",
  "Moss Minotaurs",
  "Eerie Gargoyles",
  "Spectral Sylphs",
  "Doom Merfolk",
  "Lake Hobgoblins",
  "Shadow Oni",
  "Jungle Ents",
  "Twilight Vampires",
  "Fire Kobolds",
  "Boulder Ents",
  "Stone Ents",
  "Dirt Goliaths",
  "Dark Halflings",
  "Fey Elves",
  "Thunder Dryads",
  "Fallen Undine",
  "Chasm Giants",
  "Serpent Grell",
  "Arachnid Hagravens",
  "Earthen Ogres",
]

export const RANDOM_WORDS = [
  "Lightning",
  "Thunder",
  "Ice",
  "Sand",
  "Mana",
  "Gravity",
  "Elemental",
  "Whisper",
  "Aurora"
]

export const PLANET_POSTFIXES = [
  "Alpha",
  "Prime",
  "Core",
  "Delta",
  "Gamma",
  "Epsilon",
  "Zeta",
  "Eta",
  "Theta",
  "Iota",
  "Kappa",
  "Lambda",
  "Mu",
  "Nu",
  "Xi",
  "Omicron",
  "Pi",
  "Rho",
  "Sigma",
  "Tau",
  "Upsilon",
  "Phi",
  "Chi",
  "Psi",
  "Omega"
]